['10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009']
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
['10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009', '10.1103/PhysRevD.76.013009']
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
503
http://api.crossref.org/works/10.1103/PhysRevD.76.013009
got rate limited
<urllib3.response.HTTPResponse object at 0x7f47cdc30310>
503
http://api.crossref.org/works/10.1103/PhysRevD.76.013009
got rate limited
<urllib3.response.HTTPResponse object at 0x7f47cdc13dc0>
500
http://api.crossref.org/works/10.1103/PhysRevD.76.013009
got rate limited
<urllib3.response.HTTPResponse object at 0x7f47cdcbc460>
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False False False False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False False
 False False False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False False False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False False False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False]
YAYYYYY
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True False False]
got some sort of error
HTTPConnectionPool(host='157.245.27.9', port=3128): Max retries exceeded with url: http://api.crossref.org/works/10.1103/PhysRevD.76.013009 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False]
YAYYYYY
req per second 0.7170725643634797
